### ISSUE TITLE
k8s API v1.21 and cdk8s-plus-21

### ISSUE THREAD

**Issue by civilizeddev** [cdk8s-team/cdk8s-plus-17#32]
This is just a question.

To use k8s API v1.19, v1.20 and cdk8s together,

Do I have to create my own `cdk8s-plus-19`, `cdk8s-plus-20`?

Currently, this repo provides only `cdk8s-plus-17`.

I was just wondered but still wondered even with [the documentation](https://cdk8s.io/docs/v1.0.0-beta.5/plus/).

Thank you.

**Comment by iliapolo** [comment]
Based on decision described [here](https://github.com/cdk8s-team/cdk8s-plus-17/issues/60#issuecomment-900976746) - we need to come up with a fork-merge strategy to manually push necessary changes to each of the library version lines.

**Comment by iliapolo** [comment]
As a first step, we decided we are going to create a single `cdk8s-plus` repository and have multiple release branches.

Each branch will correspond to a different k8s spec version.

So we will have, for example:

- `k8s.21`
- `k8s.20`
- `k8s.19`

The library name will be derived from the branch name, and versions are completely independent between those libraries.
This requires some projen hackery to support a different package name per release branch.

**Comment by Chriscbr** [comment]
Related: https://github.com/projen/projen/pull/1079
